### ISSUE TITLE
NoClassDefFoundError for StackNavigationFactoryKt

### ISSUE THREAD

**Issue by malliaridis** [arkivanov/Decompose#289]
### Description

I was updating my libraries and tried version `1.0.0-beta02`. When I updated the views to handle the changes in child stacks (new stack and old stack), I was getting the following exception:

### Affected Versions

- `1.0.0-beta-02`
- `1.0.0-beta-01`

### Affected Platforms

- Android (native)

### Assumptions

I assume that the changes introduced in `1.0.0-beta01` caused this error:
> Moved StackNavigation and OverlayNavigation factory functions next to the corresponding interfaces (https://github.com/arkivanov/Decompose/pull/267)

### Current Workaround

Downgrading to `1.0.0-alpha-07` resolved the error but uses the old `children()` implementation.

### Further Information

I thought it was just a caching issues, but invalidating cache and doing a clean build didn't fix the problem. I now downgraded to `1.0.0-alpha-07`.

### Stacktrace

<details>
  <summary>Stacktrace</summary>

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.malliaridis.obs.android, PID: 29961
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/arkivanov/decompose/router/stack/StackNavigationFactoryKt;
        at com.malliaridis.obs.root.integration.DefaultRootComponent.<init>(DefaultRootComponent.kt:38)
        at com.malliaridis.obs.root.integration.DefaultRootComponent.<init>(DefaultRootComponent.kt:46)
        at com.malliaridis.obs.android.MainActivity.onCreate(MainActivity.kt:41)
        at android.app.Activity.performCreate(Activity.java:8006)
        at android.app.Activity.performCreate(Activity.java:7990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8068)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.arkivanov.decompose.router.stack.StackNavigationFactoryKt" on path: DexPathList[[zip file "/data/app/~~ir-0bk5FHLcVYsMv4KBETA==/com.malliaridis.obs.android-UAfv-vP8_hf869NwJJ2eEg==/base.apk"],nativeLibraryDirectories=[/data/app/~~ir-0bk5FHLcVYsMv4KBETA==/com.malliaridis.obs.android-UAfv-vP8_hf869NwJJ2eEg==/lib/arm64, /data/app/~~ir-0bk5FHLcVYsMv4KBETA==/com.malliaridis.obs.android-UAfv-vP8_hf869NwJJ2eEg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.malliaridis.obs.root.integration.DefaultRootComponent.<init>(DefaultRootComponent.kt:38) 
        at com.malliaridis.obs.root.integration.DefaultRootComponent.<init>(DefaultRootComponent.kt:46) 
        at com.malliaridis.obs.android.MainActivity.onCreate(MainActivity.kt:41) 
        at android.app.Activity.performCreate(Activity.java:8006) 
        at android.app.Activity.performCreate(Activity.java:7990) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:8068) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) 
    ```
</details>

**Comment by arkivanov** [comment]
This looks like a transitive dependency issue. Please make sure you only use one single version of Decompose in your project. And also ensure that there are no transitive dependencies that use another version of Decompose. You may also try to rebuild your project with `--rerun-tasks -- no-build-cache` flags.

**Comment by malliaridis** [comment]
Silly me. Obviously I migrated everything except one module in my project which I took as granted. The dependency tree made that obvious. Thanks a lot for the quick support and solution. ^^
