### ISSUE TITLE
Android > Developer options > Don't keep activities ON > Crash

### ISSUE THREAD

**Issue by KangTaeJong98** [arkivanov/Decompose#419]
## When use `Don't keep activities` options. Get Crash
Turn on `Don't keep activities` and App BG > FG get crash.

### Enviroment
- compileSdk : 33
- minSdk : 33
- targetSdk : 33
- kotlin : 1.8.20
- jetbrain compose : 1.4.1
- decompose : 1.0.0
- device android version : API 33

### This is my sample code only 4 Class File.
[WebApp.zip](https://github.com/arkivanov/Decompose/files/11917658/WebApp.zip)

### This is Android Logcat
```
2023-06-30 23:51:13.300 25032-25032 Parcel                  com.taetae98.webapp.android.app      E  Class not found when unmarshalling: com.taetae98.webapp.navigation.AppRoute
                                                                                                    java.lang.ClassNotFoundException: com.taetae98.webapp.navigation.AppRoute
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4881)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:4544)
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:4324)
                                                                                                    	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
                                                                                                    	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
                                                                                                    	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
                                                                                                    	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
                                                                                                    	at android.os.BaseBundle.getValue(BaseBundle.java:374)
                                                                                                    	at android.os.BaseBundle.getValue(BaseBundle.java:357)
                                                                                                    	at android.os.BaseBundle.getValue(BaseBundle.java:350)
                                                                                                    	at android.os.Bundle.getParcelable(Bundle.java:913)
                                                                                                    	at com.arkivanov.essenty.parcelable.AndroidParcelableContainer.consume(AndroidParcelableContainer.kt:16)
                                                                                                    	at com.arkivanov.essenty.parcelable.ParcelableContainerExtKt.consumeRequired(ParcelableContainerExt.kt:9)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt$childStack$2.invoke(ChildStackFactory.kt:66)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt$childStack$2.invoke(ChildStackFactory.kt:48)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt$childStack$5.invoke(ChildStackFactory.kt:118)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt$childStack$5.invoke(ChildStackFactory.kt:106)
                                                                                                    	at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children(ChildrenFactory.kt:86)
                                                                                                    	at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children$default(ChildrenFactory.kt:61)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:106)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:48)
                                                                                                    	at com.taetae98.webapp.navigation.AppComponent.<init>(AppComponent.kt:30)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity$appComponent$2.invoke(MainActivity.kt:12)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity$appComponent$2.invoke(MainActivity.kt:12)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity.getAppComponent(MainActivity.kt:12)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity.access$getAppComponent(MainActivity.kt:10)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity$onCreate$1.invoke(MainActivity.kt:17)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity$onCreate$1.invoke(MainActivity.kt:16)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:404)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:250)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:249)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
2023-06-30 23:51:13.301 25032-25032 Parcel                  com.taetae98.webapp.android.app      E  	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3248)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3173)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:950)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1060)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:22479)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3686)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3669)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:852)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
2023-06-30 23:51:13.301 25032-25032 Parcel                  com.taetae98.webapp.android.app      E  	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: java.lang.ClassNotFoundException: com.taetae98.webapp.navigation.AppRoute
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.BootClassLoader.findClass(ClassLoader.java:1366)
                                                                                                    	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1426)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 98 more
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
2023-06-30 23:51:13.301 25032-25032 AndroidRuntime          com.taetae98.webapp.android.app      D  Shutting down VM
2023-06-30 23:51:13.302 25032-25032 AndroidRuntime          com.taetae98.webapp.android.app      E  FATAL EXCEPTION: main
                                                                                                    Process: com.taetae98.webapp.android.app, PID: 25032
                                                                                                    android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.taetae98.webapp.navigation.AppRoute
                                                                                                    	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4915)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:4544)
                                                                                                    	at android.os.Parcel.readValue(Parcel.java:4324)
                                                                                                    	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
                                                                                                    	at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
                                                                                                    	at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
                                                                                                    	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
                                                                                                    	at android.os.BaseBundle.getValue(BaseBundle.java:374)
                                                                                                    	at android.os.BaseBundle.getValue(BaseBundle.java:357)
                                                                                                    	at android.os.BaseBundle.getValue(BaseBundle.java:350)
                                                                                                    	at android.os.Bundle.getParcelable(Bundle.java:913)
                                                                                                    	at com.arkivanov.essenty.parcelable.AndroidParcelableContainer.consume(AndroidParcelableContainer.kt:16)
                                                                                                    	at com.arkivanov.essenty.parcelable.ParcelableContainerExtKt.consumeRequired(ParcelableContainerExt.kt:9)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt$childStack$2.invoke(ChildStackFactory.kt:66)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt$childStack$2.invoke(ChildStackFactory.kt:48)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt$childStack$5.invoke(ChildStackFactory.kt:118)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt$childStack$5.invoke(ChildStackFactory.kt:106)
                                                                                                    	at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children(ChildrenFactory.kt:86)
                                                                                                    	at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children$default(ChildrenFactory.kt:61)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:106)
                                                                                                    	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:48)
                                                                                                    	at com.taetae98.webapp.navigation.AppComponent.<init>(AppComponent.kt:30)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity$appComponent$2.invoke(MainActivity.kt:12)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity$appComponent$2.invoke(MainActivity.kt:12)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity.getAppComponent(MainActivity.kt:12)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity.access$getAppComponent(MainActivity.kt:10)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity$onCreate$1.invoke(MainActivity.kt:17)
                                                                                                    	at com.taetae98.webapp.android.app.MainActivity$onCreate$1.invoke(MainActivity.kt:16)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:404)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:250)
                                                                                                    	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:249)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:177)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
2023-06-30 23:51:13.302 25032-25032 AndroidRuntime          com.taetae98.webapp.android.app      E  	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:156)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3248)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                                                                                                    	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3173)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:950)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1060)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:22479)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3686)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3669)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:852)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
2023-06-30 23:51:13.303 25032-25032 AndroidRuntime          com.taetae98.webapp.android.app      E  	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: java.lang.ClassNotFoundException: com.taetae98.webapp.navigation.AppRoute
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4881)
                                                                                                    	... 95 more
                                                                                                    Caused by: java.lang.ClassNotFoundException: com.taetae98.webapp.navigation.AppRoute
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.BootClassLoader.findClass(ClassLoader.java:1366)
                                                                                                    	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1426)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 98 more
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by arkivanov** [comment]
There seems to be an issue with your class `com.taetae98.webapp.navigation.AppRoute`. Could you please provide the code of the `Parcelable` configuration class which you use with `Child Stack`?

**Comment by KangTaeJong98** [comment]
This is code.

```kotlin
import com.arkivanov.essenty.parcelable.Parcelable
import com.arkivanov.essenty.parcelable.Parcelize

@Parcelize
internal object AppRoute : Parcelable
```
```kotlin
import com.arkivanov.decompose.ComponentContext
import com.arkivanov.decompose.router.stack.ChildStack
import com.arkivanov.decompose.router.stack.StackNavigation
import com.arkivanov.decompose.router.stack.childStack
import com.arkivanov.decompose.value.Value
import com.arkivanov.essenty.parcelable.Parcelable

public class AppComponent(context: ComponentContext) : ComponentContext by context {
    private val navigation = StackNavigation<Parcelable>()

    public val stack: Value<ChildStack<Parcelable, Any>> = childStack(
        source = navigation,
        initialConfiguration = AppRoute,
        handleBackButton = true
    ) { configuration: Parcelable, componentContext: ComponentContext ->

    }
}
```
```kotlin
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import com.arkivanov.decompose.extensions.compose.jetbrains.stack.Children
import com.taetae98.webapp.navigation.AppComponent

@Composable
public fun App(
    modifier: Modifier = Modifier,
    component: AppComponent
) {
    Children(
        modifier = modifier,
        stack = component.stack
    ) {

    }
}
```
```kotlin
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import com.arkivanov.decompose.defaultComponentContext
import com.taetae98.webapp.app.App
import com.taetae98.webapp.navigation.AppComponent

class MainActivity : ComponentActivity() {
    private val context by lazy { defaultComponentContext() }
    private val appComponent by lazy { AppComponent(context = context) }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            App(component = appComponent)
        }
    }
}
```

**Comment by arkivanov** [comment]
Could you please provide the code of your `Parcelable` [configuration classes](https://arkivanov.github.io/Decompose/navigation/stack/overview/#component-configurations), including your `com.taetae98.webapp.navigation.AppRoute` class. A assume they should be in your `AppComponent`.

**Comment by KangTaeJong98** [comment]
Can you check this file? It has only 4 Kotlin file.
[WebApp.zip](https://github.com/arkivanov/Decompose/files/11917658/WebApp.zip)

**Comment by arkivanov** [comment]
You shouldn't use arbitrary `Parcelable` type. Could you please try the following?

```kotlin
public class AppComponent(context: ComponentContext) : ComponentContext by context {
    private val navigation = StackNavigation<AppRoute>()

    public val stack: Value<ChildStack<AppRoute, Any>> = childStack(
        source = navigation,
        initialConfiguration = AppRoute,
        handleBackButton = true
    ) { configuration: AppRoute, componentContext: ComponentContext ->

    }
}
```

**Comment by KangTaeJong98** [comment]
What is the `arbitrary Parcelable`?? I use this import.
```kotlin
import com.arkivanov.essenty.parcelable.Parcelable
```

**Comment by arkivanov** [comment]
You specified `Value<ChildStack<Parcelable, Any>>`, which makes the `childStack` function only aware of the `Parcelable` class itself. The function is not aware of your `AppRoute` class, and so may not be able to deserialize it. Please try specifying `AppRoute` class explicitly.

**Comment by KangTaeJong98** [comment]
Thank you!! It's solved
