### ISSUE TITLE
Retained component crashes the app

### ISSUE THREAD

**Issue by antonKozyriatskyi** [arkivanov/Decompose#428]
Wrapping a root component into `retainedComponent` results in an immediate crash on app start.

**Versions:**
- Decompose: 2.1.0-alpha-05
- Android: Api 31
- KotlinCompilerExtensionVersion: 1.4.7
- Compose-BOM: 2023.06.01
- Kotlin: 1.8.20

Before:
```
// MainActivity.onCreate()
val componentContext = DefaultAppComponentContext(
            injector = (applicationContext as App).injector,
            delegate = defaultComponentContext()
        )

        setContent {
            AppTheme(
                darkTheme = false
            ) {
                RootComponent(
                    componentContext,
                    onAppInitialised = { showSplashScreen = false }
                ).View(Modifier.fillMaxSize())
            }
        }
```
After:
```
// MainActivity.onCreate()
val componentContext = DefaultAppComponentContext(
            injector = (applicationContext as App).injector,
            delegate = defaultComponentContext()
)

val rootComponent = retainedComponent {
            RootComponent(
                componentContext,
                onAppInitialised = { showSplashScreen = false }
            )
}

 setContent {
            AppTheme(
                darkTheme = false
            ) {
                rootComponent.View(Modifier.fillMaxSize())
            }
}
```

<details><summary>Stacktrace</summary>
<p>

```
                                                                                                    Process: com.xxx.app.dev.debug, PID: 14650
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.app.dev.debug/com.xxx.app.MainActivity}: java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
                                                                                                    	at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.kt:110)
                                                                                                    	at com.arkivanov.essenty.statekeeper.AndroidExtKt.StateKeeper(AndroidExt.kt:22)
                                                                                                    	at com.arkivanov.essenty.statekeeper.AndroidExtKt.stateKeeper(AndroidExt.kt:40)
                                                                                                    	at com.arkivanov.essenty.statekeeper.AndroidExtKt.stateKeeper$default(AndroidExt.kt:39)
                                                                                                    	at com.arkivanov.decompose.RetainedComponentKt.retainedComponent(RetainedComponent.kt:83)
                                                                                                    	at com.arkivanov.decompose.RetainedComponentKt.retainedComponent(RetainedComponent.kt:46)
                                                                                                    	at com.arkivanov.decompose.RetainedComponentKt.retainedComponent$default(RetainedComponent.kt:41)
                                                                                                    	at com.xxx.app.MainActivity.onCreate(MainActivity.kt:35)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8051)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8031)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
```

</p>
</details> 

<details><summary>BaseComponent</summary>
<p>

```
public abstract class Component(componentContext: AppComponentContext) : AppComponentContext by componentContext {
    /**
     * Coroutine scope that lives as long as this component does
     * */
    protected val componentScope: CoroutineScope by lazy {
        CoroutineScope(AndroidUiDispatcher.Main + SupervisorJob())
    }

    /**
     * Coroutine scope that survives component recreation
     * */
    protected val persistentScope: CoroutineScope by lazy {
        val keeper = instanceKeeper.getOrCreate {
            PersistentScopeKeeper(CoroutineScope(AndroidUiDispatcher.Main + SupervisorJob()))
        }

        keeper.scope
    }

    protected val isFirstCreate: Boolean by lazy {
        stateKeeper.consume<RecreationMarker>(RECREATION_MARKER_KEY) == null
    }

    init {
        if (stateKeeper.isRegistered(RECREATION_MARKER_KEY).not()) {
            stateKeeper.register(RECREATION_MARKER_KEY) { RecreationMarker }
        }

        lifecycle.subscribe(
            onCreate = {
                if (isFirstCreate) {
                    onFirstCreate()
                }
                onCreate()
            },
            onDestroy = { onDestroy() }
        )
    }

    @CallSuper
    protected open fun onFirstCreate() {

    }

    @CallSuper
    protected open fun onCreate() {
        instanceKeeper.getOrCreate { FinalDestroyCaller() }.update(this)
    }

    @CallSuper
    protected open fun onDestroy() {
        componentScope.cancel()
    }

    @CallSuper
    protected open fun onFinalDestroy() {

    }

    @Parcelize
    private object RecreationMarker : Parcelable

    private class PersistentScopeKeeper(val scope: CoroutineScope) : InstanceKeeper.Instance {

        override fun onDestroy() {
            scope.cancel()
        }
    }

    private class FinalDestroyCaller : InstanceKeeper.Instance {

        private lateinit var component: Component

        fun update(component: Component) {
            this.component = component
        }

        override fun onDestroy() {
            component.onFinalDestroy()
        }
    }

    private companion object {
        const val RECREATION_MARKER_KEY = "recreation_marker"
    }
}
```
</p>
</details>

**Comment by arkivanov** [comment]
Can you share a reproducer code? It would be helpful.

**Comment by antonKozyriatskyi** [comment]
Sure. Updated the description.

**Comment by arkivanov** [comment]
It appears that you are using incorrect `ComponentContext`. Please use the one provided by `retainedComponent` function instead of `defaultComponenyContext`. See the [docs](https://arkivanov.github.io/Decompose/component/instance-retaining/#retained-components-since-v210-alpha-03).

**Comment by antonKozyriatskyi** [comment]
You're correct. My fault.
