### ISSUE TITLE
Predictive back crash

### ISSUE THREAD

**Issue by alexzhirkevich** [arkivanov/Decompose#447]
Happens on iOS.
Using predictive back while stack animation is running leads to crash with IllegalArgumentException: Key **** was used multiple times. Might be an issue in decompose-router lib, i am using it

**Comment by alexzhirkevich** [comment]
Animation from [here](https://kotlinlang.slack.com/archives/C03H3N51SKT/p1687530708014979?thread_ts=1687520418.786979&cid=C03H3N51SKT)

**Comment by arkivanov** [comment]
Also happens on Android U.

**Comment by arkivanov** [comment]
The full stack trace doesn't show any connections to Decompose. Will investigate it further.

```
FATAL EXCEPTION: main
Process: com.arkivanov.sample.app, PID: 5347
java.lang.IllegalArgumentException: Key Config_0 was used multiple times 
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:89)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl$SaveableStateProvider$1$1.invoke(SaveableStateHolder.kt:88)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
	at androidx.compose.runtime.CompositionImpl.applyLateChanges(Composition.kt:859)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:640)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:878)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@c069b9, androidx.compose.ui.platform.MotionDurationScaleImpl@3991fe, StandaloneCoroutine{Cancelling}@b72bd5f, AndroidUiDispatcher@c07c3ac]

```

**Comment by alexzhirkevich** [comment]
Probably the simplest fix is to disable predictive back while animation is running if possible

**Comment by arkivanov** [comment]
Unfortunately with the current API design, the predictive back gesture Composable is not aware of the underlying animation. There likely will be an API change to address this case.

**Comment by arkivanov** [comment]
Seems like I was able to disable the gesture while inner animation is playing, without API changes for now.
