### ISSUE TITLE
Cannot create LifecycleRegistry

### ISSUE THREAD

**Issue by SWRHARD** [arkivanov/Decompose#464]
After update Intellij Idea to new version, I have a compilation error, when start to create **LifecycleRegistry()**, At the previous version of IDEA, all was good

- Desktop platform
- IntelliJ IDEA 2023.2.1 (Community Edition) Build #IC-232.9559.62, built on August 23, 2023 (
- decompose version: com.arkivanov.decompose:decompose: 2.0.1
- decompose extensions: com.arkivanov.decompose:extensions-compose-jetbrains-jvm: 2.0.1

**old version of IDEA, where error doesn't exist**: IntelliJ IDEA 2023.1.3 (Community Edition) Build #IC-231.9161.38, built on June 20, 2023

**code:**

      @OptIn(ExperimentalDecomposeApi::class)
      fun main() {
          val lifecycle = LifecycleRegistry()
          val root = DefaultRootComponent(DefaultComponentContext(lifecycle)) <- error at this line
      
          application {
              val state = rememberWindowState().apply {
                  size = DpSize(windowWidth, windowHeight)
              }
      
              TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE
      
              LifecycleController(lifecycle, state)
              Window(
              ) {
              }
          }
      }

**stacktrace:**

    Exception in thread "main" java.lang.NoClassDefFoundError: com/arkivanov/essenty/utils/internal/FreezingKt
	    at com.arkivanov.essenty.lifecycle.LifecycleRegistryImpl.<init>(LifecycleRegistryImpl.kt:10)
	    at com.arkivanov.essenty.lifecycle.LifecycleRegistryKt.LifecycleRegistry(LifecycleRegistry.kt:23)
	    at com.arkivanov.essenty.lifecycle.LifecycleRegistryKt.LifecycleRegistry(LifecycleRegistry.kt:15)
	    at presentation.app.ApplicationKt.main(Application.kt:39)
	    at presentation.app.ApplicationKt.main(Application.kt)
    Caused by: java.lang.ClassNotFoundException: com.arkivanov.essenty.utils.internal.FreezingKt
	    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	    ... 5 more

**Comment by arkivanov** [comment]
First of all, this looks like a runtime error, not a compilation error. And it looks like something is wrong with your environment.

Please try [invalidating caches](https://www.jetbrains.com/help/idea/invalidate-caches.html), and also recompiling your project with `--rerun-tasks --no-build-cache` flags.

**Comment by dalaus** [comment]
I got the same error when I included the sqldelight plugin in my project. I was able to avoid the error by creating a gradle run configuration with "run" in "Tasks and arguments" field.

**Comment by arkivanov** [comment]
Closing this for now.

**Comment by sdzshn3** [comment]
@SWRHARD Are you able to fix it ?
I'm trying to run it in Android Studio but it is failing with the same error.
