### ISSUE TITLE
java.lang.IllegalStateException: Another supplier is already registered with the key: com.attendace.leopard.migrate.presentation.screen.home.components.HomeNavigationHelper.router

### ISSUE THREAD

**Issue by adelsaramii** [arkivanov/Decompose#497]
im using navigation in an another navigation and when i use push in parent navigation all works fine but when i call pop in parent navigation crash shows up with this log

java.lang.IllegalStateException: Another supplier is already registered with the key: com.attendace.leopard.migrate.presentation.screen.home.components.HomeNavigationHelper.router
at com.arkivanov.essenty.statekeeper.DefaultStateKeeperDispatcher.register(DefaultStateKeeperDispatcher.kt:44)
at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children(ChildrenFactory.kt:93)
at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children$default(ChildrenFactory.kt:61)
at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:91)
at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:40)
at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack$default(ChildStackFactory.kt:31)
at io.github.xxfast.decompose.NavigatorKt.rememberChildStack(Navigator.kt:36)
at io.github.xxfast.decompose.router.RouterKt.rememberRouter(Router.kt:55)
at com.attendace.leopard.migrate.presentation.screen.home.HomeScreenKt.HomeContentNavigation(HomeScreen.kt:101)
at com.attendace.leopard.migrate.presentation.screen.home.HomeScreenKt.HomeScreen(HomeScreen.kt:54)
at com.attendace.leopard.migrate.presentation.screen.navigation.MainNavigationKt$MainContentNavigation$4$1.invoke(MainNavigation.kt:133)

why? and how can i fix it

**Comment by arkivanov** [comment]
Can you show some code? How this can be reproduced?

**Comment by adelsaramii** [comment]
ok in this senario we have 5 Screens 1.Parent Screen 2.Splash Screen 3.Home Screen 4.NewsList Screen 5.Interests Screen
in tree view -> 
- Parent Screen is the base Screen that is a host navigation for Splash Screen and Home Screen
- Home Screen is the parent Screen that is a host navigation for NewsList Screen and Interests Screen

App runs -> Parent Screen shows Splash and after that Home -> In Home we have NewsList on first stack and we navigate  to Interests -> till now all works fine -> and now if we navigate to Splash screen in Parent Screen it would crash

the crash log:
java.lang.IllegalStateException: Another supplier is already registered with the key: com.attendace.leopard.migrate.presentation.screen.home.components.HomeNavigationHelper.router
at com.arkivanov.essenty.statekeeper.DefaultStateKeeperDispatcher.register(DefaultStateKeeperDispatcher.kt:44)
at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children(ChildrenFactory.kt:93)
at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children$default(ChildrenFactory.kt:61)
at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:91)
at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:40)
at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack$default(ChildStackFactory.kt:31)
at io.github.xxfast.decompose.NavigatorKt.rememberChildStack(Navigator.kt:36)
at io.github.xxfast.decompose.router.RouterKt.rememberRouter(Router.kt:55)
at com.attendace.leopard.migrate.presentation.screen.home.HomeScreenKt.HomeContentNavigation(HomeScreen.kt:101)
at com.attendace.leopard.migrate.presentation.screen.home.HomeScreenKt.HomeScreen(HomeScreen.kt:54)
at com.attendace.leopard.migrate.presentation.screen.navigation.MainNavigationKt$MainContentNavigation$4$1.invoke(MainNavigation.kt:133)

it refers to Home navigation Router
and if i take Home router to the Parent screen and pass it as parameter to Home Screen it would be no crash
why child router crashs if parent router make a navigation
im i need to clear child router before navigate with parent router?

**Comment by arkivanov** [comment]
Ok, it seems that you are using [Decompose-Router](https://github.com/xxfast/Decompose-Router) by @xxfast. This error might be already fixed in the latest version [0.5.0](https://github.com/xxfast/Decompose-Router/releases/tag/0.5.0). Could you please try? Please mind the migration guide described in the release notes.

**Comment by adelsaramii** [comment]
i just checked it out and yes it was fixed by new version
