### ISSUE TITLE
Pages with childPages() is causing my app to crash, as default HorizontalPager Composable used internally can't be found.

### ISSUE THREAD

**Issue by mustfaibra** [arkivanov/Decompose#502]
I'm Using PagesNavigation to implement a Bottom Navigation component, my definition as follow :

In BottomNavComponentImp

```kotlin
private val navigation = PagesNavigation<BottomNavConfig>()
private val _pages = this.childPages(
  source = navigation,
  initialPages = {
    Pages(
      items = listOf(BottomNavConfig.Home),
      selectedIndex = 0,
    )
  },
  childFactory = ::createChildPageFactor
)
```
And in my UI
```kotlin
Pages(
  modifier = Modifier
    .fillMaxWidth()
    .weight(1f),
  pages = pages,
  onPageSelected = {
    bottomNavComponent.onNewPageSelected(index = it)
  },
) { _, page ->
  when (page) {
    ...
  }
}
```

Here is where the crash happen in the library:
```kotlin
@ExperimentalFoundationApi
@ExperimentalDecomposeApi
fun defaultHorizontalPager(): Pager =
    { pageCount, modifier, state, key, pageContent ->
        HorizontalPager(
            pageCount = pageCount,
            modifier = modifier,
            state = state,
            key = key,
            pageContent = pageContent,
        )
    }
```

And here is the crash's backtrack :
```kotlin
FATAL EXCEPTION: main
                 Process: com.mustfaibra.qpaymultiplatform.android, PID: 3286
                 java.lang.NoSuchMethodError: No static method HorizontalPager-AlbwjTQ(ILandroidx/compose/ui/Modifier;Landroidx/compose/foundation/pager/PagerState;Landroidx/compose/foundation/layout/PaddingValues;Landroidx/compose/foundation/pager/PageSize;IFLandroidx/compose/ui/Alignment$Vertical;Landroidx/compose/foundation/gestures/snapping/SnapFlingBehavior;ZZLkotlin/jvm/functions/Function1;Landroidx/compose/ui/input/nestedscroll/NestedScrollConnection;Lkotlin/jvm/functions/Function3;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/foundation/pager/PagerKt; or its super classes (declaration of 'androidx.compose.foundation.pager.PagerKt' appears in /data/app/com.mustfaibra.qpaymultiplatform.android-zMiTRHEeTYcPKgnakgEUAA==/base.apk)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.pages.ComposableSingletons$PagesKt$lambda-1$1.invoke(Pages.kt:93)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.pages.ComposableSingletons$PagesKt$lambda-1$1.invoke(Pages.kt:92)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:221)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.pages.PagesKt.Pages(Pages.kt:77)
                 	at com.mustfaibra.qpaymultiplatform.ui.screens.BottomNavPageKt.BottomNavPage(BottomNavPage.kt:33)
                 	at com.mustfaibra.qpaymultiplatform.ui.ComposableSingletons$QPayAppKt$lambda-1$1.invoke(QPayApp.kt:156)
                 	at com.mustfaibra.qpaymultiplatform.ui.ComposableSingletons$QPayAppKt$lambda-1$1.invoke(QPayApp.kt:66)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1$1.invoke(Children.kt:31)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1$1.invoke(Children.kt:30)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1.invoke(Children.kt:30)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt$Children$1.invoke(Children.kt:29)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.animation.EmptyStackAnimation.invoke(EmptyStackAnimation.kt:26)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.stack.ChildrenKt.Children(Children.kt:29)
                 	at com.mustfaibra.qpaymultiplatform.ui.QPayAppKt$QPayApp$2$1.invoke(QPayApp.kt:63)
                 	at com.mustfaibra.qpaymultiplatform.ui.QPayAppKt$QPayApp$2$1.invoke(QPayApp.kt:53)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at com.mustfaibra.qpaymultiplatform.ui.QPayAppKt$QPayApp$2.invoke(QPayApp.kt:49)
                 	at com.mustfaibra.qpaymultiplatform.ui.QPayAppKt$QPayApp$2.invoke(QPayApp.kt:48)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
```

**Comment by arkivanov** [comment]
What Decompose and Compose versions are you using? `HorizontalPager` is still experimental and may change, which causes binary compatibility issues like this one. You can fix it by using the same version of Compose as used by Decompose (you can check Decompose release notes for versions).

**Comment by mustfaibra** [comment]
For compose, I'm using version **1.5.1**, and for Decompose I'm using **2.0.0**.

Hmm. 
Ok, I will give it a try!

**Comment by arkivanov** [comment]
Yeah, there were [breaking changes](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.5.0-alpha04) in Jetpack Compose Pager API. You can update Decompose to 2.1.x.

**Comment by arkivanov** [comment]
Closing this for now. Feel free to reopen if there are any issues.
