### ISSUE TITLE
crash: on 3.0.0-alpha07  java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by EvgenBES** [arkivanov/Decompose#660]
` Process: com.blackstone.decomposetest, PID: 27808
                 java.lang.NoSuchMethodError: No virtual method observe(Lkotlin/jvm/functions/Function1;)Lcom/arkivanov/decompose/Cancellation; in class Lcom/arkivanov/decompose/value/Value; or its super classes (declaration of 'com.arkivanov.decompose.value.Value' appears in /data/data/com.blackstone.decomposetest/code_cache/.overlay/base.apk/classes.dex)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.SubscribeAsStateKt$subscribeAsState$1.invoke(SubscribeAsState.kt:23)
                 	at com.arkivanov.decompose.extensions.compose.jetbrains.SubscribeAsStateKt$subscribeAsState$1.invoke(SubscribeAsState.kt:22)
                 	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82)
                 	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1137)
                 	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:828)
                 	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
                 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1041)
                 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:142)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1191)
                 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:133)
                 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:183)
                 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
                 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1266)
                 	at android.view.View.dispatchAttachedToWindow(View.java:20483)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2419)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1954)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8180)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:878)
                 	at android.view.Choreographer.doFrame(Choreographer.java:811)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loop(Looper.java:223)
                 	at android.app.ActivityThread.main(ActivityThread.java:7698)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
`
                 	
dependencies:
  implementation("com.arkivanov.decompose:decompose:3.0.0-alpha07")
  implementation("com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2")
platform: android

  implementation("com.arkivanov.decompose:decompose:2.2.2") - work ok

**Comment by arkivanov** [comment]
This happens because you are using different versions of Decompose modules, they should always be the same. Please see the migration guide [here](https://github.com/arkivanov/Decompose/releases/tag/3.0.0-alpha01), and also check release notes of every newer release (just in case). Use `3.0.0-alpha07` version for both `decompose` and `extensions-compose` modules.

**Comment by EvgenBES** [comment]
@arkivanov I use only 2 dependencies from decompose
implementation("com.arkivanov.decompose:decompose:3.0.0-alpha07")
implementation("com.arkivanov.decompose:extensions-compose-jetbrains:2.2.2")

when i try add 
implementation("com.arkivanov.decompose:extensions-compose-jetbrains:3.0.0-alpha07")
I got error :
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.arkivanov.decompose:extensions-compose-jetbrains:3.0.0-alpha07.
Searched in the following locations:
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.arkivanov.decompose:extensions-compose-jetbrains:3.0.0-alpha07.

  - https://dl.google.com/dl/android/maven2/com/arkivanov/decompose/extensions-compose-jetbrains/3.0.0-alpha07/extensions-compose-jetbrains-3.0.0-alpha07.pom
  - https://repo.maven.apache.org/maven2/com/arkivanov/decompose/extensions-compose-jetbrains/3.0.0-alpha07/extensions-compose-jetbrains-3.0.0-alpha07.pom
Required by:

**Comment by arkivanov** [comment]
Yes, as I mentioned earlier, pease see the migration guide [here](https://github.com/arkivanov/Decompose/releases/tag/3.0.0-alpha01), and also check release notes of every newer release (just in case). Use `3.0.0-alpha07` version for both `decompose` and `extensions-compose` modules.

**Comment by EvgenBES** [comment]
Yep. My mistake.

> The extensions-compose-jetpack module is removed, the extensions-compose-jetbrains module is renamed to extensions-compose
