### ISSUE TITLE
Some Problem in decompose = "3.0.0" and decompose-router = "0.5.1", kotlin = 2.0.0-RC3

### ISSUE THREAD

**Issue by Crazy-Kyle** [arkivanov/Decompose#714]
java.lang.NoSuchMethodError: No static method defaultComponentContext(Landroidx/savedstate/SavedStateRegistryOwner;)Lcom/arkivanov/decompose/DefaultComponentContext; in class Lcom/arkivanov/decompose/DefaultComponentContextBuilderKt; or its super classes (declaration of 'com.arkivanov.decompose.DefaultComponentContextBuilderKt' appears in /data/data/space.aigod.platformapp/code_cache/.overlay/base.apk/classes7.dex)
                                                                                                    	at io.github.xxfast.decompose.router.DefaultRouterContextKt.defaultRouterContext(DefaultRouterContext.kt:9)
                                                                                                    	at space.aigod.platformapp.MainActivity.onCreate(MainActivity.kt:29)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8577)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8541)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3884)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4049)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8348)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by pradeep-magzter** [comment]
can you please share, what is the fix? @Crazy-Kyle

**Comment by malliaridis** [comment]
Since you already created an [issue](https://github.com/xxfast/Decompose-Router/issues/96) in decompose-router too, I think the [answer provided there](https://github.com/xxfast/Decompose-Router/issues/96#issuecomment-2126650746) is sufficient, but here for a quick lookup:

`decompose-router` version `0.5.1` and `0.7.0` do not supported Decompose 3.0.0 yet. decompose-router has upgraded the Decompose dependency to 3.0.0 in a [recent commit](https://github.com/xxfast/Decompose-Router/commit/9822ae9ea34cba80329c3f9ebfdff39200cd8f05) that has not yet been released. Decompose 3.0.0 introduced some breaking changes which very likely cause the error. Therefore, you should wait until the next version of decompose-router is released.
