### ISSUE TITLE
NotOnMainThreadException false-positive

### ISSUE THREAD

**Issue by DatL4g** [arkivanov/Decompose#720]
Facing this stacktrace on desktop applications.

```gradle
com.arkivanov.decompose.mainthread.NotOnMainThreadException: Expected to be called on the main thread, but was main
	at com.arkivanov.decompose.mainthread.CheckMainThreadKt.checkMainThread(CheckMainThread.kt:7)
	at com.arkivanov.decompose.router.children.EventProcessor.process(ChildrenFactory.kt:157)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$9.invoke(ChildrenFactory.kt:124)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt$children$9.invoke(ChildrenFactory.kt:124)
	at com.arkivanov.decompose.Relay.drainLoop(Relay.kt:40)
	at com.arkivanov.decompose.Relay.accept(Relay.kt:21)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children(ChildrenFactory.kt:145)
	at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children$default(ChildrenFactory.kt:105)
	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:107)
	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:39)
	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:72)
	at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack$default(ChildStackFactory.kt:64)
	at dev.datlag.burningseries.ui.navigation.RootComponent.<init>(RootComponent.kt:22)
	at dev.datlag.burningseries.MainKt.runWindow(Main.kt:56)
	at dev.datlag.burningseries.MainKt.main(Main.kt:40)
```

It's not crashing at least but a bit confusing.

Example: https://github.com/DatL4g/Burning-Series/tree/6.x

**Comment by arkivanov** [comment]
Thanks! Please see the docs to fix the issue: https://arkivanov.github.io/Decompose/component/overview/#jvmdesktop-with-compose.
