### ISSUE TITLE
Child Page

### ISSUE THREAD

**Issue by zokirjonkarimov** [arkivanov/Decompose#780]
kotlin = "2.0.20"                                                                                                   	
decompose = "3.1.0"  

java.lang.NoSuchMethodError: No static method HorizontalPager-xYaah8o(Landroidx/compose/foundation/pager/PagerState;Landroidx/compose/ui/Modifier;Landroidx/compose/foundation/layout/PaddingValues;Landroidx/compose/foundation/pager/PageSize;IFLandroidx/compose/ui/Alignment$Vertical;Landroidx/compose/foundation/gestures/snapping/SnapFlingBehavior;ZZLkotlin/jvm/functions/Function1;Landroidx/compose/ui/input/nestedscroll/NestedScrollConnection;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/foundation/pager/PagerKt; or its super classes (declaration of 'androidx.compose.foundation.pager.PagerKt' appears in /data/app/~~vfkxWPfV9pc31BpRjcVr1Q==/uz.isds.beauty-efF8wOGzyYoaXeVkXDi9pw==/base.apk)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.pages.ComposableSingletons$PagesKt$lambda-1$1.invoke(Pages.kt:114)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.pages.ComposableSingletons$PagesKt$lambda-1$1.invoke(Pages.kt:113)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:193)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.pages.PagesKt.Pages(Pages.kt:91)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.pages.PagesKt.Pages(Pages.kt:41)
                                                                                                    	at uz.isds.beauty.ui.screen.info.SalonInfoScreenKt.SalonInfoContent(SalonInfoScreen.kt:257)
                                                                                                    	at uz.isds.beauty.ui.screen.info.SalonInfoScreenKt.SalonInfoScreen(SalonInfoScreen.kt:76)
                                                                                                    	at uz.isds.beauty.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:34)
                                                                                                    	at uz.isds.beauty.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:28)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt$Children$1$1.invoke(Children.kt:34)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt$Children$1$1.invoke(Children.kt:33)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:85)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt$Children$1.invoke(Children.kt:33)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt$Children$1.invoke(Children.kt:32)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.animation.SimpleStackAnimation$Child$1.invoke(SimpleStackAnimation.kt:27)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.animation.SimpleStackAnimation$Child$1.invoke(SimpleStackAnimation.kt:25)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.animation.FadeKt$fade$1.invoke(Fade.kt:18)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.animation.FadeKt$fade$1.invoke(Fade.kt:17)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:161)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.animation.DefaultStackAnimator.invoke(DefaultStackAnimator.kt:45)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.animation.SimpleStackAnimation.Child(SimpleStackAnimation.kt:21)
2024-09-21 18:53:29.048 20270-20270 AndroidRuntime          uz.isds.beauty                       E  	at com.arkivanov.decompose.extensions.compose.stack.animation.AbstractStackAnimation.invoke(AbstractStackAnimation.kt:40)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt.Children(Children.kt:32)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt.Children(Children.kt:48)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt.Children$lambda$1(Unknown Source:22)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt.$r8$lambda$uWR6hJkw_1GCpb7edfnakWv-V9c(Unknown Source:0)
                                                                                                    	at com.arkivanov.decompose.extensions.compose.stack.ChildrenKt$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3116)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3607)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3552)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:827)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@6bff05e, androidx.compose.ui.platform.MotionDurationScaleImpl@1aa2c3f, StandaloneCoroutine{Cancelling}@6aa390c, AndroidUiDispatcher@f242255]

**Comment by arkivanov** [comment]
This is a binary compatibility issue. Decompose `3.1.0` depends on Multiplatform Compose `1.6.10`, which depends on Jetpack Compose `1.6.7`. Here are possible solutions.

1. Use Multiplatform Compose `1.6.10` or Jetpack Compose `1.6.7`.
2. Update Decompose to `3.2.0-beta01` and use Compose `1.7.x`.
3. Specify [pager](https://github.com/arkivanov/Decompose/blob/5555af7c7ae864c8510a61a73dba2a2593dc1d00/extensions-compose/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/pages/ChildPages.kt#L30) argument for `ChildPages` composable function and call `HorizontalPager` manually.

**Comment by zokirjonkarimov** [comment]
decompose 3.2.0-beta01 ChildPages() working correctly. thanks
